#Создаем deployment с nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-store
  template:
    metadata:
      labels:
        app: web-store
    spec:
      affinity:                                           # Здесь как раз делаем, чтобы были задействованы
        podAntiAffinity:                                  # нодов, чтобы не пришлось резко все чинить
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-store
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-app
        image: nginx:alpine
        resources:           # Устанавливаем кол-во ресурсов
          limits:
            memory: "128M"   # Наш максимум по ресурсу
          requests:          # А тут минимум
            memory: "128M"
            cpu: "100m"
        ports:
          - containerPort: 80
        livenessProbe:      # Запуск нашего приложения 5-10 сек, поэтому в ход пошли healthchecks
          httpGet:          # У нас будут HTTP запросы
            path: /
            port: 80
          initialDelaySeconds: 15 
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80            
          initialDelaySeconds: 5
          periodSeconds: 5
        

---
apiVersion: autoscaling/v2 # HPA, где видно что у нас поды от 1 до 4, и что при >20% будет поднимать новые
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20


---
apiVersion: v1 # поднимаем простенький сервис,чтобы взглянуть на приложение из браузера
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
     env  : prod
spec:
  selector:
    app: web-store      
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80 
      targetPort: 80
      nodePort: 30009
  type: NodePort